branches:
  - 'develop'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - assets:
        - path: target/wise.war
          label: Build
